[project]
name = "enzyme-design"
version = "0.1.0"
description = "AI for enzyme design"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "numpy>=2.4.2",
    "scipy>=1.17.1",
    "pandas>=3.0.1",
    "matplotlib>=3.10.8",
    "seaborn>=0.13.2",
    "biopython>=1.86",
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.5",
    "transformers>=5.2.0",
    "accelerate>=1.12.0",
    "fair-esm>=2.0.0",
    "torchao>=0.16.0",
    "ipykernel>=7.2.0",
    "plotly>=6.6.0",
    "scikit-learn>=1.8.0",
    "nltk>=3.9.4",
    "pyspark>=4.1.1",
    "umap-learn>=0.5.12",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }
